dbt_training:
  outputs:
    dev:
      account: pi21224.us-central1.gcp
      database: ANALYTICS_DEV
      password: "{{ ENV_VAR('DBT_PASSWORD') }}"
      role: DBT_TRAINING
      schema: MROONEY
      threads: 1
      type: snowflake
      user: "{{ ENV_VAR('DBT_USER')}}"
      warehouse: DBT_TRAINING_WH
    prod:
      account: pi21224.us-central1.gcp
      database: ANALYTICS
      password: "{{ ENV_VAR('DBT_PASSWORD') }}"
      role: DBT_TRAINING
      schema: MROONEY
      threads: 1
      type: snowflake
      user: "{{ ENV_VAR('DBT_USER')}}"
      warehouse: DBT_TRAINING_WH

  target: dev