name: CI

on:
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with: 
          python-version: '3.9'

      - name: Install dbt
        run: pip install dbt-snowflake

      - name: Run dbt build
        run: dbt build --profiles-dir .